### ISSUE TITLE
The URIs of some object and data properties don't have underscores

### ISSUE THREAD

**Issue by maxneal** [maxneal/OPB#1]
These URIs should be renamed using the "OPB_{ID}" convention. Previously I created a program that corrected any OPB class URIs that not conforming to the convention. But it didn't examine the object and data properties. I can re-run the program and include the properties.

**Comment by dcookUW** [comment]
Unless you see a problem with properties, go ahead and make the changes. 

Dan

**Comment by maxneal** [comment]
I fixed this in commit c5bccd6b4743169ca0fced4f6cea1620ea34100d.
